name: CMake

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Environment setup
      run: sudo tools/installers/essentials.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build/masscalculator-core-${{matrix.build_type}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build/masscalculator-core-${{matrix.build_type}} --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build/masscalculator-core-${{matrix.build_type}}
      run: ctest -C ${{matrix.build_type}}

    - name: Package
      run: echo 'Package stage is in progress'

    - name: Deploy
      run: echo 'Deploy stage is in progress'

  trigger:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true

    steps:
      - name: Send repository dispatch event
        uses: actions/trigger@v1
        with:
          event: masscalculator-core-pr-merged
          repository: MassCalculator/masscalculator.github.io
          token: ${{secrets.GITHUB_TOKEN}}
